### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by ngryman** [jugglinmike/srcdoc-polyfill#7]
Hey,

It seems the package is not published.

**Comment by jugglinmike** [comment]
That's correct! Would it help you if it were available on npm?

**Comment by ngryman** [comment]
Yes, I manage all my dependencies via `npm`, even for frontend development.

**Comment by broerse** [comment]
[ember-twiddle](http://ember-twiddle.com/) could maybe use this for W10 Edge browser support. Ember is moving away from bower to npm, So it would help if it is available on npm.

**Comment by mischkl** [comment]
bump. We use Browserify. This would be very helpful! :)

**Comment by jugglinmike** [comment]
Hey everybody,

I know npm is encouraging adoption by modules of all kinds, but I still feel weird pushing non-CommonJS code there. I've implemented a UMD wrapper for this project so that it's easier to consume with RequireJS/Browserify/etc. This is technically a breaking change, so I've published a new version (0.2.0).

Long story short: the library is now available on npm. https://www.npmjs.com/package/srcdoc-polyfill

Enjoy!

**Comment by mischkl** [comment]
awesome, thanks! :)

**Comment by ngryman** [comment]
Thanks!

**Comment by broerse** [comment]
Thanks!
